### ISSUE TITLE
IFP address sync failure

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#661]
paybutton-dev  | 2|next  | 2023-09-12T02:03:04: Invalid `prisma.address.findMany()` invocation:
paybutton-dev  | 2|next  | 2023-09-12T02:03:04: 
paybutton-dev  | 2|next  | 2023-09-12T02:03:04: 
paybutton-dev  | 2|next  | 2023-09-12T02:03:04: Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at pn.handleRequestError (/home/node/src/node_modules/@prisma/client/runtime/library.js:176:6477)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at pn.handleAndLogRequestError (/home/node/src/node_modules/@prisma/client/runtime/library.js:176:5907)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at pn.request (/home/node/src/node_modules/@prisma/client/runtime/library.js:176:5786)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async t._request (/home/node/src/node_modules/@prisma/client/runtime/library.js:179:10484)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async fetchAllUserAddresses (/home/node/src/.next/server/chunks/4784.js:496:10)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async getUserUncachedAddresses (/home/node/src/.next/server/chunks/4784.js:187:21)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async getPaymentList (/home/node/src/.next/server/pages/api/dashboard.js:230:25)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async getUserDashboardData (/home/node/src/.next/server/pages/api/dashboard.js:239:23)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async __WEBPACK_DEFAULT_EXPORT__ (/home/node/src/.next/server/pages/api/dashboard.js:276:26)
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:     at async Object.apiResolver (/home/node/src/node_modules/next/dist/server/api-utils/node.js:372:9) {
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:   code: 'P2024',
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:   clientVersion: '4.13.0',
paybutton-dev  | 2|next  | 2023-09-12T02:03:04:   meta: { connection_limit: 5, timeout: 10 }
paybutton-dev  | 2|next  | 2023-09-12T02:03:04: }

**Comment by Klakurka** [comment]
It managed to get to ~800 results then it died.

Also, the tx amounts are wrong when clicking into the button and viewing the transactions. The values are all negative (few hundred XEC each ).

**Comment by Klakurka** [comment]
![image](https://github.com/PayButton/paybutton-server/assets/4713204/8a5882c6-aa5d-49da-898a-317678936b90)
